# Generated by Django 5.0.2 on 2024-02-08 06:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0003_alter_register_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(0)])),
                ('adm_no', models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(4), django.core.validators.MinLengthValidator(0)])),
                ('gender', models.CharField(choices=[('male', 'Male '), ('female', 'Female')], default='male', max_length=6)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('dob', models.DateField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=15, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='public.register')),
            ],
        ),
    ]
