# Generated by Django 5.0.2 on 2024-02-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_photo/'),
        ),
    ]
