# Generated by Django 5.0.2 on 2024-02-08 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_alter_register_phone'),
        ('student', '0002_alter_studentprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to=models.Q(('is_student', True)), on_delete=django.db.models.deletion.CASCADE, related_name='student', to='public.register'),
        ),
    ]
