# Generated by Django 5.0.1 on 2024-02-09 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='adm_no',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='register_no',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
