# Generated by Django 5.0.1 on 2024-02-10 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_studentprofile_adm_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='adm_no',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mothers_name',
            field=models.CharField(blank=True, default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='register_no',
            field=models.PositiveIntegerField(blank=True, default=1, unique=True, validators=[django.core.validators.MinValueValidator(10)]),
            preserve_default=False,
        ),
    ]
