# Generated by Django 5.0.1 on 2024-02-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_studentprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(default='../media/profile_photo/c-3.png', null=True, upload_to='profile_photo/'),
        ),
    ]
