# Generated by Django 5.0.1 on 2024-02-14 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0010_delete_departmentclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfileClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(limit_choices_to=models.Q(('is_teacher', True)), on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='public.register')),
            ],
        ),
    ]
