# Generated by Django 5.0.1 on 2024-02-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_course_subject_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
