# Generated by Django 5.0.1 on 2024-02-14 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_studentacademicmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentacademicmodel',
            name='sem_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.semester'),
            preserve_default=False,
        ),
    ]
