# Generated by Django 5.0.1 on 2024-02-14 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_studentacademicmodel_sem_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademicmodel',
            name='sem_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.semester'),
        ),
    ]
