# Generated by Django 5.0.1 on 2024-02-14 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_studentacademicmodel_sem_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.semester')),
                ('student_academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.studentacademicmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.subject')),
            ],
        ),
    ]
