# Generated by Django 5.0.1 on 2024-02-15 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_subjectmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerAttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.BooleanField(default=False)),
                ('student_academic', models.ForeignKey(limit_choices_to=models.Q(('course', 'computer')), on_delete=django.db.models.deletion.CASCADE, to='teacher.studentacademicmodel')),
            ],
        ),
    ]
