# Generated by Django 5.0.1 on 2024-02-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_alter_computerattendancemodel_student_academic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('number', 'course')},
        ),
    ]
