# Generated by Django 5.0.1 on 2024-02-15 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_alter_computerattendancemodel_student_academic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerattendancemodel',
            name='student_academic',
            field=models.ForeignKey(limit_choices_to=models.Q(('sem_details__course__course_name', 'computer')), on_delete=django.db.models.deletion.CASCADE, to='teacher.studentacademicmodel'),
        ),
        migrations.CreateModel(
            name='ElectronicsAttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.BooleanField(default=False)),
                ('student_academic', models.ForeignKey(limit_choices_to=models.Q(('sem_details__course__course_name', 'electronics')), on_delete=django.db.models.deletion.CASCADE, to='teacher.studentacademicmodel')),
            ],
        ),
    ]
