# Generated by Django 5.0.1 on 2024-02-15 09:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_alter_computerattendancemodel_student_academic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerattendancemodel',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 15)),
        ),
        migrations.AlterField(
            model_name='computerattendancemodel',
            name='student_academic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.studentacademicmodel'),
        ),
    ]
