# Generated by Django 5.0.1 on 2024-02-21 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0020_alter_computerattendancemodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerattendancemodel',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 21)),
        ),
    ]
