# Generated by Django 5.0.1 on 2024-02-23 05:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0021_alter_computerattendancemodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerattendancemodel',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 23)),
        ),
        migrations.CreateModel(
            name='Internalmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField()),
                ('assignment_marks', models.FloatField(default=0.0)),
                ('internal_marks', models.FloatField(default=0.0)),
                ('student_academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.studentacademicmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.subject')),
            ],
        ),
    ]
