# Generated by Django 5.0.1 on 2024-02-23 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0024_totalmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalmark',
            name='student_academic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.studentacademicmodel'),
        ),
    ]
