# Generated by Django 5.0.1 on 2024-02-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0026_alter_totalmark_student_academic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalmark',
            name='subject_mark',
        ),
        migrations.RemoveField(
            model_name='totalmark',
            name='total_internal_marks',
        ),
        migrations.RemoveField(
            model_name='totalmark',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='totalmark',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
