# Generated by Django 5.0.1 on 2024-02-23 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0027_remove_totalmark_subject_mark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalmark',
            name='student_academic',
        ),
        migrations.AddField(
            model_name='totalmark',
            name='subject_mark',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.subjectmark'),
            preserve_default=False,
        ),
    ]
