# Generated by Django 5.0.1 on 2024-02-23 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0028_remove_totalmark_student_academic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalmark',
            name='id',
        ),
        migrations.AlterField(
            model_name='totalmark',
            name='subject_mark',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teacher.subjectmark'),
        ),
    ]
