# Generated by Django 5.0.1 on 2024-02-23 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0029_remove_totalmark_id_alter_totalmark_subject_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalmark',
            old_name='total_sum',
            new_name='total_marks',
        ),
        migrations.RemoveField(
            model_name='totalmark',
            name='subject_mark',
        ),
        migrations.AddField(
            model_name='totalmark',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalmark',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalmark',
            name='student_academic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.studentacademicmodel'),
            preserve_default=False,
        ),
    ]
