# Generated by Django 5.0.1 on 2024-02-24 05:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0031_alter_totalmark_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerattendancemodel',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 24)),
        ),
        migrations.AlterField(
            model_name='totalmark',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.semester'),
        ),
    ]
