# Generated by Django 5.0.1 on 2024-02-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0032_alter_computerattendancemodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmark',
            name='marks_obtained',
            field=models.FloatField(default=0.0),
        ),
    ]
