# Generated by Django 5.0.1 on 2024-02-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0033_alter_subjectmark_marks_obtained'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('evimg', models.ImageField(blank=True, upload_to='event-photo/')),
            ],
        ),
    ]
