# Generated by Django 5.0.1 on 2024-02-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField(max_length=8)),
                ('phone', models.PositiveIntegerField(default=0, max_length=10)),
                ('address', models.TextField(max_length=255)),
                ('is_student', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_principal', models.BooleanField(default=False)),
            ],
        ),
    ]
