# Generated by Django 5.0.1 on 2024-02-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=8),
        ),
    ]
