# Generated by Django 5.0.2 on 2024-02-08 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_register_name_alter_register_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(0)]),
        ),
    ]
