# Generated by Django 5.0.1 on 2024-02-09 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_alter_register_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(0)]),
        ),
    ]
