# Generated by Django 5.0.1 on 2024-02-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_alter_register_address_alter_register_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='is_principal',
        ),
    ]
