# Generated by Django 5.0.1 on 2024-02-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_remove_register_is_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=20, null=True)),
                ('dept_code', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
