# Generated by Django 5.0.1 on 2024-02-10 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_departmentclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(0)]),
        ),
    ]
