# Generated by Django 5.0.1 on 2024-02-10 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_alter_register_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True, validators=[django.core.validators.MaxLengthValidator(15), django.core.validators.MinLengthValidator(0)]),
        ),
    ]
