# Generated by Django 5.0.1 on 2024-02-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_alter_register_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentClass',
        ),
    ]
